# prowlarr config pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-pv
  namespace: media
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.113
    path: /mnt/external/config/prowlarr/config
  storageClassName: nfs-storage
---
