# qbittorrent config
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
  namespace: media
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.113
    path: /mnt/external/config/qbittorrent/
  storageClassName: nfs-storage
---
# qbittorrent downloads
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-pv
  namespace: media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.113
    path: /mnt/external/config/qbittorrent/downloads
  storageClassName: nfs-storage
---
