# jackett deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: media
  labels:
    app: jackett
spec:
  selector:
    matchLabels:
      app: jackett
  replicas: 1
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett:latest
        ports:
        - containerPort: 9117
        volumeMounts:
        - mountPath: /config/Jackett
          name: jackett-config
      volumes:
      - name: jackett-config
        persistentVolumeClaim:
          claimName: jackett-config-pvc
