# flaresolverr deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: media
  labels:
    app: flaresolverr
spec:
  selector:
    matchLabels:
      app: flaresolverr
  replicas: 1
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: flaresolverr/flaresolverr:latest
        ports:
        - containerPort: 8191
        volumeMounts:
        - mountPath: /config/Flaresolverr
          name: flaresolverr-config
      volumes:
      - name: flaresolverr-config
        persistentVolumeClaim:
          claimName: flaresolverr-config-pvc
