# Create NFS PersistentVolumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
  namespace: media
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.113
    path: /mnt/external/config/radarr/
  storageClassName: nfs-storage
---
