apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prominence
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage
---
