apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
  type: LoadBalancer
---
