apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: {{ .Values.namespace }}
  labels:
    app: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  replicas: 1
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8096
        volumeMounts:
        - mountPath: /media/Shows
          name: external-shows
        - mountPath: /media/Movies1
          name: movies1
        - mountPath: /media/Movies2
          name: movies2
        - mountPath: /config
          name: jellyfin-config
        - mountPath: /cache
          name: jellyfin-cache
      volumes:
        - name: external-shows
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.paths.shows }}
        - name: movies1
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.paths.movies1 }}
        - name: movies2
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.paths.movies2 }}
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: jellyfin-cache
          persistentVolumeClaim:
            claimName: jellyfin-cache-pvc
---
